### PR TITLE
Update Catalog with skypilot#1204

### PR DESCRIPTION
**Pull request by Michaelvll**
[skypilot#1204](https://github.com/skypilot-org/skypilot/pull/1204)

### CODE REVIEW

**Comment by concretevitamin** [comment]
A thought for future: it may be interesting for the fetchers to print out a report to say: N new instance types; on-demand: N prices have changed in M zones; spot: … etc. This can be useful to put in this repository’s readme or put in SkyPilot’s release notes.

**Comment by Michaelvll** [comment]
The following are the updates in the new catalog, where `#resources` indicates new `(InstanceType, Region, AvailabilityZone)` tuples appear in the table
```
       #resources  #prices  #spot_prices
aws           365      387          4462
azure          67       70          2602
gcp           264      489          1381
```

**Comment by concretevitamin** [comment]
Should this be updating v2 vs. adding a v3? @WoosukKwon

**Comment by WoosukKwon** [comment]
> Should this be updating v2 vs. adding a v3?

@concretevitamin I think we should keep it as v2 since there's no schema change.

**Review by WoosukKwon — APPROVED** [review]
Thanks @Michaelvll for submitting this PR! I've tested some instances and they worked well.

**Comment by concretevitamin** [comment]
Since there are some new instance info (InstanceType, Region, AvailabilityZone), does this mean an “older” v2 can’t launch some of these, while a “newer” v2 suddenly can? From a user’s perspective this seems a bit weird.

**Comment by WoosukKwon** [comment]
@concretevitamin Oh I just realized that the schema has changed. Considering the discussion we had on the v1 -> v2 update, we should bump up the schema version.

**Comment by Michaelvll** [comment]
Good point! I just bump up to v3. PTAL

**Review by WoosukKwon — APPROVED** [review]
LGTM!

**Pull request merged**
