### PR TITLE
[AWS] Check region matches the request

### PR DESCRIPTION
**Pull request by Michaelvll**
Related to https://github.com/skypilot-org/skypilot/pull/1505

Add the integrity checking option to the github action to have a safeguard for any unexpected failure, i.e. do not update the catalog if any error happens.

Update the catalog with the new `fetch_aws.py` from https://github.com/skypilot-org/skypilot/pull/1505 (with more regions).

### CODE REVIEW

**Review by concretevitamin — COMMENTED** [review]
Looks good generally, but not sure what "region integrity" means (see the main repo PR's comments).

**Review by concretevitamin — APPROVED** [review]
For discussion: any reason we should have this flag rather than always default to strict checks?

**Comment by Michaelvll** [comment]
> For discussion: any reason we should have this flag rather than always default to strict checks?

It is because if a user accidentally run the `fetch_aws` locally, it will fail if we set the flag to True by default and their account does not have access to the regions listed.

**Comment by WoosukKwon** [comment]
nit: typo (mathes -> matches) in the title of the PR?

**Review by concretevitamin — APPROVED** [review]

**Pull request merged**
